name: CI/CD Pipeline

# Trigger pipeline on pushes to main branch or tags starting with "V"
on:
  push:
    branches:
      - main
    tags:
      - 'V*'  # Runs on any tag starting with "V"
  workflow_dispatch:

jobs:
  # 1: Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Check out the code
        uses: actions/checkout@v3

      # Set up Python v3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests witn pytest
      - name: Run Tests
        run: |
          pytest

  # 2: Build and push Docker image
  build_and_push_docker:
    needs: test  # Checks that tests pass before going forward
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/V3.0'  # Run only on these tags

    steps:
      # Checkout code
      - name: Check out the code
        uses: actions/checkout@v3
        
      # Authenticate with DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with specific tag
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bankapp:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bankapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/bankapp:V3.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bankapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bankapp:V3.0
